language: ruby
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.2
gemfile:
  - gemfiles/5.0.gemfile
  - gemfiles/6.0.gemfile
before_install:
  - gem install bundler -v 1.11.2
  - sudo apt-get -qq update
  - sudo apt-get install -y ghostscript
before_script:
  - cd spec/dummy && bundle exec rake db:test:prepare && cd -
  - cd spec && bash generate_jpegs.sh && cd -
